


export const COMENT_SEND = 'COMENT_SEND' ; 


// export const COMENT_CHANGED = 'COMENT_CHANGED' ; 

export const FETCH_COMMENTS = 'FETCH_COMMENTS' ;
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS' ; 